Data Encoding
1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

Nominal/OHE Encoding
One hot encoding also known as nominal encoding is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represnted as a binary vector where each bit corresponds to a unique category. For example if we have a categorical variable 'color' with three possible values(red, green, blue) we can represent it one hot encoding as follows:

1. Red:[1,0,0]
2. Green:[0,1,0]
3. Blue:[0,0,1]

In [ ]:
# Disadvantages
# if we have 100 categories we will have 100 features
# sparse matrix - overfitting

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
#Create a simple dataframe
df = pd.DataFrame({'color':['red','blue','green','green','red','blue']})

In [3]:
#Create an instance of Onehotencoder
encoder=OneHotEncoder()

In [9]:
#Perform fit and transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [10]:
import pandas as pd
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [11]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [12]:
#if we add new data
encoder.transform([['blue']]).toarray()

/Users/pravarikakosanam/Desktop/mathematics for ai/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [13]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

Label Encoding
Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have categorical variable color with three possible values(red,green,blue), we can represent it using label encoding as follows:

Red:1
Green:2
Blue:3

In [14]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [16]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [17]:
lbl_encoder.fit_transform(df[['color']])

/Users/pravarikakosanam/Desktop/mathematics for ai/venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [18]:
lbl_encoder.transform([['red']])

/Users/pravarikakosanam/Desktop/mathematics for ai/venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [19]:
lbl_encoder.transform([['blue']])

/Users/pravarikakosanam/Desktop/mathematics for ai/venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [20]:
lbl_encoder.transform([['green']])

/Users/pravarikakosanam/Desktop/mathematics for ai/venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

when ever we assign unique numbers then in label encoder the model may think it is rank
Ordinal Encoder

#Ordinal Encoding
It is used to encode categorical data that have intrisic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example if we have a categorical variable "educational level" with four possible values(high school, college, graduate, post-graduate), we can represnt it using ordinal encoding as follows:

High school:1
College: 2
Graduate: 3
Post-graduate:4

In [25]:
#Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [26]:
#Ccreate a sample dataframe with an ordinal variable
df = pd.DataFrame({'size':['small','medium','large','medium','small','large']})

In [27]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [28]:
#Create an instance of ordinalencoder and then fit_trannsform
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [29]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [30]:
#newdata
encoder.transform([['small']])

/Users/pravarikakosanam/Desktop/mathematics for ai/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])